agent:
  name: my_test_agent
  description: "OpenAI chat creation"

templates:

- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: TextInput
  class_name: TextInput
  template_input: InputTemplate
  attributes:
    text : what is AI?

- template_name: OpenAIChat
  class_name: OpenAIChatWrapper
  template_input: InputTemplate
  attributes:
    model : gpt-4-turbo
    openai_init: {}
    create: {}

